apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: cx11-ubuntu
  namespace: shoot--foobar--hcloud
providerSpec:
  imageName: "ubuntu-20.04"
  zone: "hel1-dc2"
  serverType: "cx11-ceph"
  sshFingerprint: "ssh-rsa invalid"
secretRef: # If required
  name: hcloud-test-secret
  namespace: default # Namespace where the controller would watchroot
