apiVersion: machine.sapcloud.io/v1alpha1
kind: Machine
metadata:
  name: test1
  namespace: shoot--foobar--hcloud
spec:
  class:
    kind: MachineClass
    name: cx11-ubuntu
    namespace: shoot--foobar--hcloud
